### ISSUE TITLE
Getting error Unexpected HTTP response code when retrieving header: 500

### ISSUE THREAD

**Issue by sudogitclone** [Orygin/gofoil#1]
Hello, I tried using gofoil on Windows with Awoo Installer v1.3.3 on AMS 0.13.0

Started gofoil with:

```
gofoil -root D:\\ -folders switch/updates -ip 192.168.1.123 -port 8000
```

Start LAN install on Awoo

Open http://192.168.1.123:8000 and enter Switch IP address 192.168.1.100

NSP files are listed in Awoo

Try to install an NSP

An error appears in Awoo:

```
Failed to install ....

PerformRequest:102: Unexpected HTTP response code when retrieving header: 500
```

Here is gofoil log from cmd:

```
2020/07/13 15:20:02 Starting server at 192.168.1.123:8000, with root D:\\ + swit
ch/updates
2020/07/13 15:20:14 / :
2020/07/13 15:20:17 / :
2020/07/13 15:20:17 192.168.1.100
Sending NSP list: [192.168.1.123:8000/files/D:%2Fswitch%2Fupdates%2Fmy.nsp]
2020/07/13 15:20:21 /files/D:%2Fswitch%2Fupdates%2Fmy.nsp : bytes=256-259
2020/07/13 15:20:21 /files/D:%2Fswitch%2Fupdates%2Fmy.nsp :
```

I have no issue doing the same NSP install using NS-USBloader

**Comment by Orygin** [comment]
Hello,

I believe the issue is related to the argument used for the root folder.
In the code I had to escape the backslash, but it seems that it is not needed when setting it via cli flag.
This causes the removal of the root path from the files path to not work, and the server can't find the file.

Please try with "-root D:\\", and I'll update the readme with the correct example.

**Comment by sudogitclone** [comment]
Great it now works! I am able to install the NSP with Awoo after using D:\ for root argument. I will close the issue, thank you.
